import type { Metadata } from "next";
import { Inter, Montserrat, Roboto, Lora } from "next/font/google";
import "./globals.css";
import { DropdownProvider } from "./utility/contexts/DropdownContext";
import { BagProvider } from './utility/contexts/BagContext';

const inter = Inter({ 
  subsets: ["latin"],
  variable: "--font-inter",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
})

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
  style: ['normal', 'italic'],
  display: 'swap',
  variable: "--font-roboto",
})

const lora = Lora ({
  subsets: ["latin"],
  variable: "--font-lora"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${montserrat.variable} ${roboto.variable} ${lora.variable}`}>
        <DropdownProvider>
          <BagProvider>
            {children}
          </BagProvider>
        </DropdownProvider>
      </body>
    </html>
  );
}
